### ISSUE TITLE
How to get the training data?

### ISSUE THREAD

**Issue by czhxiaohuihui** [XiaoyuanYi/StyIns#2]
请问怎样获取训练数据? 

可以给个链接或者上传一下原始的实验数据嘛...

**Comment by XiaoyuanYi** [comment]
@czhxiaohuihui  你好，不好意思之前在忙其他事情，没能及时回复。

Yelp的数据我们直接使用了Shen等人预处理的版本： https://github.com/shentianxiao/language-style-transfer/tree/master/data/yelp

GYAFC的数据原作者保留了版权，我们没有权限直接复制给其他人，如下链接是GYAFC原作者的github：
https://github.com/raosudha89/GYAFC-corpus
可以按照上述链接中的指示，发邮件给原作者以获取数据集。
